// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNMDtk9nLUg-2myIERgXM0JaPyGcvI4Yo',
    appId: '1:369950550432:web:23304b03b520ca865cdcc5',
    messagingSenderId: '369950550432',
    projectId: 'ticktaktoe',
    authDomain: 'ticktaktoe-8a468.firebaseapp.com',
    storageBucket: 'ticktaktoe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkYuJsPB8kdGMvUgm2QBU9D3b9sI6q0lc',
    appId: '1:369950550432:android:35700434604872e25cdcc5',
    messagingSenderId: '369950550432',
    projectId: 'ticktaktoe',
    storageBucket: 'ticktaktoe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHUvVMB8ejXRCPylTD5jbOPJFwI7aRK2g',
    appId: '1:369950550432:ios:1f742b40d4ab31055cdcc5',
    messagingSenderId: '369950550432',
    projectId: 'ticktaktoe',
    storageBucket: 'ticktaktoe.firebasestorage.app',
    iosBundleId: 'com.example.ticktaktoe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHUvVMB8ejXRCPylTD5jbOPJFwI7aRK2g',
    appId: '1:369950550432:ios:1f742b40d4ab31055cdcc5',
    messagingSenderId: '369950550432',
    projectId: 'ticktaktoe',
    storageBucket: 'ticktaktoe.firebasestorage.app',
    iosBundleId: 'com.example.ticktaktoe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNMDtk9nLUg-2myIERgXM0JaPyGcvI4Yo',
    appId: '1:369950550432:web:9a2a68cf6404f2be5cdcc5',
    messagingSenderId: '369950550432',
    projectId: 'ticktaktoe',
    authDomain: 'ticktaktoe-8a468.firebaseapp.com',
    storageBucket: 'ticktaktoe.firebasestorage.app',
  );
}
